apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: a5a647e2-7311-4669-85c4-5be1e64990b3
    type: postgres
    url: postgres
    user: postgres
    database: postgres
    basicAuth: false
    isDefault: true
    readOnly: true
    jsonData:
        postgresVersion: 1200
        sslmode: disable
        timescaledb: true
    secureJsonData:
      password: admin