{
 "title": "Data Rates",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Message Count Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  route AS metric,\n  count(rayqueuecountbacklog + rayqueuecountcurrent) AS \"count\"\nFROM data\nWHERE\n  $__timeFilter(time) \nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  route AS metric,\n  avg(rayqueuecountbacklog + rayqueuecountcurrent) AS \"avg\"\nFROM data\nWHERE\n  $__timeFilter(time) \nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  route AS metric,\n  avg(responseTime) AS \"responseTime\"\nFROM data\nWHERE\n  $__timeFilter(time) \nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  route AS metric,\n  avg(nReplicas) AS \"responseTime\"\nFROM data\nWHERE\n  $__timeFilter(time) AND nReplicas is not null\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select \nroute, \nNOW() - last(time, time) as last_seen\nfrom data \nGROUP BY route\n"
    }
   ]
  }
 ]
}